version: "3"
services:
    api:
        build:
            args:
                NODE_ENV: development
        volumes:
            - ./node_modules
            - ./.next
            - ./:/app
        ports:
            - 3030:3030
    postgres:
        ports:
            - 5431:5432